main: Tp1_pm.java
	javac Tp1_pm.java

run: main
	java Tp1_pm ./data/pesquisadores.txt ./data/grafo_pesquisadores.txt ./data/grafo_artigos_pesquisadores.txt ./data/grafo_citacoes.txt ./data/veiculos.txt ./data/artigos_veiculos.txt

clean:
	rm Tp1_pm.class